// Horizon API URLs
export const HORIZON_MAINNET = 'https://horizon.stellar.org';
export const HORIZON_TESTNET = 'https://horizon-testnet.stellar.org';

// Dashboard API (for lumen supply and historical data)
// In production, use the full URL; in dev, Vite proxy handles it
export const DASHBOARD_API = import.meta.env.DEV ? '' : 'https://dashboard.stellar.org';

// StatusPage API
// In production, use the full URL; in dev, Vite proxy handles it
export const STATUSPAGE_API = import.meta.env.DEV 
  ? '/api/statuspage/v2/summary.json'
  : 'https://9sl3dhr1twv1.statuspage.io/api/v2/summary.json';

// Network types
export type NetworkType = 'mainnet' | 'testnet';

export const getHorizonUrl = (network: NetworkType): string => {
  return network === 'mainnet' ? HORIZON_MAINNET : HORIZON_TESTNET;
};

// Known accounts for labeling
export const KNOWN_ACCOUNTS: Record<string, string> = {
  'GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7': 'Poloniex',
  'GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3': 'Bittrex',
  'GCGNWKCJ3KHRLPM3TM6N7D3W5YKDJFL6A2YCXFXNMRTZ4Q66MEMZ6FI2': 'Kraken',
  'GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A': 'Binance',
  'GC4KAS6W2YCGJGLP633A6F6AKTCV4WSLMTMIQRSEQE5QRRVKSX7THV6S': 'btcid',
  'GBV4ZDEPNQ2FKSPKGJP2YKDAIZWQ2XKRQD4V4ACH3TCTFY6KPY3OAVS7': 'Changelly',
  'GCO2IP3MJNUOKS4PUDI4C7LGGMQDJGXG3COYX3WSB4HHNAHKYV5YL3VC': 'Binance',
  'GDCIUCGL7VEMMF6VYJOW75KQ5ZCLHAQBRM6EPFTKCRWUYVUOOYQCKC5A': 'Mobius.network',
  'GALAXYVOIDAOPZTDLHILAJQKCVVFMD4IKLXLSZV5YHO7VY74IWZILUTO': 'Void Account',
  'GBEZOC5U4TVH7ZY5N3FLYHTCZSI6VFGTULG7PBITLF5ZEBPJXFT46YZM': 'Upgrade Reserve',
};

// SDF Accounts (for supply calculations)
export const SDF_ACCOUNTS = {
  escrowJan2022: 'GD2D6JG6D3V52ZMPIYSVHYFKVNIMXGYVLYJQ3HYHG5YDPGJ3DCRGPLTP',
  escrowJan2023: 'GA2VRL65L3ZFEDDJ357RGI3MAOKPJZ2Z3IJTPSC24I4KDTNFSVEQURRA',
  developerSupportHot: 'GCKJZ2YVECFGLUDJ5T7NZMJPPWERBNYHCXT2MZPXKELFHUSYQR5TVHJQ',
  developerSupportHot2: 'GC3ITNZSVVPOWZ5BU7S64XKNI5VPTRSBEXXLS67V4K6LEUETWBMTE7IH',
  directDevelopment: 'GB6NVEN5HSUBKMYCE5ZOWSK5K23TBWRUQLZY3KNMXUZ3AQ2ESC4MY4AQ',
  directDevelopmentHot2: 'GATL3ETTZ3XDGFXX2ELPIKCZL7S5D2HY3VK4T7LRPD6DW5JOLAEZSZBA',
  directDevelopmentHot4: 'GAKGC35HMNB7A3Q2V5SQU6VJC2JFTZB6I7ZW77SJSMRCOX2ZFBGJOCHH',
  directDevelopmentHot5: 'GAPV2C4BTHXPL2IVYDXJ5PUU7Q3LAXU7OAQDP7KVYHLCNM2JTAJNOQQI',
  infrastructureGrants: 'GCVJDBALC2RQFLD2HYGQGWNFZBCOD2CPOTN3LE7FWRZ44H2WRAVZLFCU',
  currencySupport: 'GAMGGUQKKJ637ILVDOSCT5X7HYSZDUPGXSUW67B2UKMG2HEN5TPWN3LQ',
  currencySupportHot: 'GANII5Y2LABEBK74NWNKS4NREX2T52YTBGQDRDKVBFRIIF5VE4ORYOVY',
  enterpriseFund: 'GDUY7J7A33TQWOSOQGDO776GGLM3UQERL4J3SPT56F6YS4ID7MLDERI4',
  newProducts: 'GCPWKVQNLDPD4RNP5CAXME4BEDTKSSYRR4MMEL4KG65NEGCOGNJW7QI2',
  inAppDistribution: 'GDKIJJIKXLOM2NRMPNQZUUYK24ZPVFC6426GZAEP3KUK6KEJLACCWNMX',
  inAppDistributionHot: 'GAX3BRBNB5WTJ2GNEFFH7A4CZKT2FORYABDDBZR5FIIT3P7FLS2EFOZZ',
  inAppDistributionHot2: 'GDWXQOTIIDO2EUK4DIGIBLEHLME2IAJRNU6JDFS5B2ZTND65P7J36WQZ',
  marketingSupport: 'GBEVKAYIPWC5AQT6D4N7FC3XGKRRBMPCAMTO3QZWMHHACLHTMAHAM2TP',
  marketingSupportHot: 'GBI5PADO5TEDY3R6WFAO2HEKBTTZS4LGR77XM4AHGN52H45ENBWGDFOH',
};

// Friendbot account (testnet)
export const FRIENDBOT_ACCOUNT = 'GAIH3ULLFQ4DGSECF2AR555KZ4KNDGEKN4AFI4SU2M7B43MGK3QJZNSR';

// Void account (burned lumens)
export const VOID_ACCOUNT = 'GALAXYVOIDAOPZTDLHILAJQKCVVFMD4IKLXLSZV5YHO7VY74IWZILUTO';

// Network upgrade reserve account
export const UPGRADE_RESERVE_ACCOUNT = 'GBEZOC5U4TVH7ZY5N3FLYHTCZSI6VFGTULG7PBITLF5ZEBPJXFT46YZM';

// Original supply amount
export const ORIGINAL_SUPPLY = '100000000000';

// Ledger calculations
export const LEDGERS_IN_AVERAGE = 200;
export const LEDGERS_FOR_CHARTS = 100;
